apiVersion: v1
kind: Service
metadata:
  name: dfly-service
  namespace: kube-system
  labels:
    app: dfly-service
spec:
  type: LoadBalancer
  selector:
    app: dfly-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: kube-system
  labels:
    app: dfly-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dfly-service
  template:
    metadata:
      labels:
        app: dfly-service
    spec:
      containers:
      - name: dfly-app
        image: 816360740237.dkr.ecr.us-west-2.amazonaws.com/dfly_images:v1
        ports:
        - containerPort: 8080
