apiVersion: v1
kind: Service
metadata:
  name: dfly-lb
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: dfly-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
